### ISSUE TITLE
CTF - Check cFS's initial start up events

### ISSUE THREAD

**Issue by blueoceanwater** [nasa/CTF#1]
This is reported on behalf of CTF user. She has an app which generates some events when starting. However, TO needs to receive “EnableCfsOutput” command to send out such events/telemetry.  The events to check happened before TO receives “EnableCfsOutput”. So CTF could not receive/check such events. Need to find a way to address it.

**Comment by tngo67** [comment]
Since there won't be any telemetry being transmitted prior to enabling TO telemetry output, the verification of events that occurred before that will have to be via inspection method, and not via automatic testing method.  The test conductor can perform post analysis of the events log captured by CTF to verify such events did occurred when that test case was executed.

**Comment by skliper** [comment]
We use the cFE event log to verify startup events.  As long as the cFE event log is configured big enough to capture all startup events, once the system is up and configured you can send a command to EVS to dump the log, transfer the log to the local machine and look for the event (we've got plugins to do this).  This approach works for both the SP0 and Linux, whereas depending on how you setup initialization you may not be able to capture SP0 startup events in the CTF event log.

**Comment by tngo67** [comment]
We can add your plugins to the CTF core plug-ins.  Great idea, @skliper.

**Comment by blueoceanwater** [comment]
will be released in v1.7
